"de_de_prefix": +49
"de_de_header": 89
"en_gb_prefix": +44
"en_gb_header": 77001
"en_us_prefix": +1
"en_us_header": 71840
"en_ca_prefix": +1
"en_ca_header": 41655
"en_nz_prefix": +64
"en_nz_header": 449
"en_sg_prefix": +65
"en_sg_header": 965
"nl_nl_prefix": +31
"nl_nl_header": 6199
"en_au_prefix": +61
"en_au_header": 4915
"fr_fr_prefix": +33
"fr_fr_header": 6231
"he_il_prefix": +972
"he_il_header": 5841
"ja_jp_prefix": +81
"ja_jp_header": 4263

